/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetali;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;





/**
 *
 * @author Ali-M
 */
public class afficher_m extends javax.swing.JFrame {
    int i =0;
    private String[][] Tableau = new String[10000][];
public Connection con ;
    public Statement st;
    public ResultSet rst;
    String url = "jdbc:mysql://localhost:3306/salle?autoReconnect=true&useSSL=false";
    String utilisateur = "ali";
    String motDePasse = "alimtibaa";
    public JTable tableau ;
    public Statement st1;
    public JTable tableau1;
    public DefaultTableModel model;
   public JScrollPane s ;
     /**
     * Creates new form afficher_m
     */

    public afficher_m() {
        initComponents();
    this.setVisible(true);
    this.setTitle("Afficher Membres");
    this.setLocationRelativeTo(null);
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.setResizable(false);
    String  title[] = {"ID", "NOM", "PRENOM", "NUM TEL", "EMAIL", "DATE NAIS", "ETAT ABO"};
    try {
Class.forName("com.mysql.jdbc.Driver");
con= DriverManager.getConnection( url, utilisateur, motDePasse );
st=con.createStatement();
model = new DefaultTableModel(Tableau, title);
tableau = new JTable(model);
tableau.setAutoResizeMode(0);
ResultSet result = st.executeQuery("SELECT M.ID_MEMBRE,M.NOM,M.PRENOM,M.NUM_TEL,M.EMAIL,M.DATE_NAIS, A.ETATABONEMENT"
        + "  FROM membre M, abonement A where M.ID_MEMBRE = A.ID_MEMBRE;");
ResultSetMetaData resultMeta = (ResultSetMetaData) result.getMetaData();
tableau.setModel(DbUtils.resultSetToTableModel(result)); 
 add(new JScrollPane(tableau), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 340, 200));
 tableau.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION); 
            }
        catch(Exception ex){
        System.out.println(ex);}      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 532));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTE MEMBRE");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 86, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetali/home-banner.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 130));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetali/7.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ali-M\\Desktop\\Projetali\\8.png")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 60, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetali/9.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 60, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetali/10.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 60, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, 30));

        jLabel3.setText("Rechercher");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetali/11.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        membre h = new membre();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (tableau.getSelectedRow() != -1) {
             model.removeRow(tableau.getSelectedRow());   
           try {
int s =  (int) tableau.getValueAt(tableau.getSelectedRow(),0);
int id = 0;
st=con.createStatement();
ResultSet rst0 = st.executeQuery( "SELECT ID_ABONEMENT  FROM abonement where ID_MEMBRE = '"+s+"';" );  
 if (rst0.next()) {
 id = rst0.getInt(1);
 } 
 int rst4 = st.executeUpdate( "DELETE from apartient where ID_ABONEMENT = '"+id+"';");
 int rst2 = st.executeUpdate( "DELETE from abonement where ID_MEMBRE = '"+s+"';");
 int rst1 = st.executeUpdate( "DELETE from membre where ID_MEMBRE = '"+s+"';");
 

  JOptionPane info = new JOptionPane();
info.showMessageDialog(null, "Suppression Aboutie", "INFO", JOptionPane.INFORMATION_MESSAGE);
jButton2.updateUI();
  }
        catch(Exception ex){
        System.out.println("Rien selectionnée");}    
       
          
        } 
      
if (tableau1.getSelectedRow() != -1) {
           try {
int s =  (int) tableau1.getValueAt(tableau1.getSelectedRow(),0);
int id = 0;
st=con.createStatement();
ResultSet rst0 = st.executeQuery( "SELECT ID_ABONEMENT  FROM abonement where ID_MEMBRE = '"+s+"';" );  
 if (rst0.next()) {
 id = rst0.getInt(1);
 } 
 int rst4 = st.executeUpdate( "DELETE from apartient where ID_ABONEMENT = '"+id+"';");
 int rst2 = st.executeUpdate( "DELETE from abonement where ID_MEMBRE = '"+s+"';");
 int rst1 = st.executeUpdate( "DELETE from membre where ID_MEMBRE = '"+s+"';");
  JOptionPane info1 = new JOptionPane();
info1.showMessageDialog(null, "Suppression Aboutie", "INFO", JOptionPane.INFORMATION_MESSAGE);
info1.updateUI();
            }
        catch(Exception ex){
        System.out.println("Rien selectionnée");}    
           
          
       
          
        }
 

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   

        String  title[] = {"ID", "NOM", "PRENOM", "NUM TEL", "EMAIL", "DATE NAIS"};
    try {
 
 model = new DefaultTableModel(Tableau, title);
tableau1 = new JTable(model);
tableau1.setAutoResizeMode(0);
ResultSet result = st.executeQuery("SELECT M.ID_MEMBRE,M.NOM,M.PRENOM,M.NUM_TEL,M.EMAIL,M.DATE_NAIS, A.ETATABONEMENT"
        + "  FROM membre M, abonement A where M.ID_MEMBRE = A.ID_MEMBRE AND( NOM = '"+jTextField1.getText()+"'"
                + "OR PRENOM = '"+jTextField1.getText()+"' OR M.ID_MEMBRE = '"+jTextField1.getText()+"'"
                        + "OR DATE_NAIS = '"+jTextField1.getText()+"');");
 ResultSetMetaData resultMeta = (ResultSetMetaData) result.getMetaData();
 tableau1.setModel(DbUtils.resultSetToTableModel(result)); 
 s = new JScrollPane(tableau1);
 this.getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 340, 100));
 tableau1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION); 
  jButton1.updateUI();
         
 

    }
        catch(Exception ex){
        System.out.println(ex);}  
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if (tableau.getSelectedRow() != -1) {
           
           Modifier_m md = new Modifier_m();
           try {
int s =  (int) tableau.getValueAt(tableau.getSelectedRow(),0);

st=con.createStatement();
 
 ResultSet rst4 = st.executeQuery( "SELECT M.ID_MEMBRE,M.NOM,M.PRENOM,M.NUM_TEL,M.EMAIL,M.DATE_NAIS,M.IMAGE"
         + "  FROM membre M where ID_MEMBRE = '"+s+"';" ); 
 if (rst4.next()) {
     md.setid(rst4.getInt(1));
     md.setnom(rst4.getString(2));
     md.setprenom(rst4.getString(3));
     md.settel(rst4.getString(4));
     md.setmail(rst4.getString(5));
     md.setdate(rst4.getString(6));
     md.setimg(rst4.getString(7));
 } 
 ResultSet rst5 = st.executeQuery( "SELECT ETATABONEMENT FROM abonement  where ID_MEMBRE = '"+s+"';" ); 
 if (rst5.next()) {
     md.setetat(rst5.getString(1));
     
 } 
  
            }
        catch(Exception ex){
        System.out.println("");}    
       
         this.setVisible(false); 
        }   
       
       
       if (tableau1.getSelectedRow() != -1) {
           
           Modifier_m md = new Modifier_m();
           try {
int s =  (int) tableau1.getValueAt(tableau1.getSelectedRow(),0);

st=con.createStatement();
 
 ResultSet rst4 = st.executeQuery( "SELECT M.ID_MEMBRE,M.NOM,M.PRENOM,M.NUM_TEL,M.EMAIL,M.DATE_NAIS,M.IMAGE"
         + "  FROM membre M where ID_MEMBRE = '"+s+"';" ); 
 if (rst4.next()) {
     md.setid(rst4.getInt(1));
     md.setnom(rst4.getString(2));
     md.setprenom(rst4.getString(3));
     md.settel(rst4.getString(4));
     md.setmail(rst4.getString(5));
     md.setdate(rst4.getString(6));
     md.setimg(rst4.getString(7));
 } 
 ResultSet rst5 = st.executeQuery( "SELECT ETATABONEMENT FROM abonement  where ID_MEMBRE = '"+s+"';" ); 
 if (rst5.next()) {
     md.setetat(rst5.getString(1));
     
 } 
  
            }
        catch(Exception ex){
        System.out.println("");}    
       this.setVisible(false);
          
        } 
       this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   this.remove(s);
   jTextField1.setText("");
   jButton5.updateUI();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(afficher_m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(afficher_m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(afficher_m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(afficher_m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new afficher_m().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
