/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetali;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.nio.file.FileSystem;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Ali-M
 */
public class Modifier_m extends javax.swing.JFrame {
private int id ;
String url = "jdbc:mysql://localhost:3306/salle?autoReconnect=true&useSSL=false";
    String utilisateur = "ali";
    String motDePasse = "alimtibaa";
    public Connection con ;
    public Statement st;
    public String path;
    public String path1;
    File file ;
    /**
     * Creates new form Modifier_m
     */
    public Modifier_m() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Modifier Membres");
    this.setLocationRelativeTo(null);
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.setResizable(false);
    this.setLayout(null);
   
   
    try {
Class.forName("com.mysql.jdbc.Driver");
con= DriverManager.getConnection( url, utilisateur, motDePasse );
st=con.createStatement();
 }
        catch(Exception ex){
        System.out.println(ex);}  
    }
    public void setnom(String n){this.jTextField5.setText(n); }
    public void setprenom(String p){this.jTextField6.setText(p);}
    public void settel(String t){this.jTextField7.setText(t);}
    public void setmail(String m){this.jTextField8.setText(m);}
    public void setdate(String d){this.jTextField9.setText(d);}
    public void setimg(String i){
        path1 = i ;
        this.jTextField10.setText(i);
    jLabel5.setIcon(new ImageIcon(path1));
   
    jLabel5.setBounds(10, 150, 90, 90);}
    public void setetat(String e){this.jTextField11.setText(e);}
    public void setid(int i){this.id = i; }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODIFIER");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 86, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetali/home-banner.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 130));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Modifier un Membre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel8.setText("Nom :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        jLabel9.setText("Prenom :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        jLabel10.setText("Tel :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 20));

        jLabel11.setText("E-Mail :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, 20));

        jLabel12.setText("Date-N :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, 20));

        jLabel13.setText("Image :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, 20));

        jLabel14.setText("Etat :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, 20));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 70, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 70, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 70, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 70, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 70, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 70, -1));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 70, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetali/10.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 60, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetali/7.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 100, 100));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 30, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetali/12.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        membre h = new membre();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
              
    try {    
        st.executeUpdate("update membre set NOM='"+jTextField5.getText()+"',PRENOM='"+jTextField6.getText()+"'"
                + ",NUM_TEL='"+jTextField7.getText()+"',EMAIL='"+jTextField8.getText()+"'"
                        + ",DATE_NAIS='"+jTextField9.getText()+"',IMAGE='"+jTextField10.getText()+"'"
                                + "where ID_MEMBRE ='"+id+"' ;");
        
        st.executeUpdate("update abonement set ETATABONEMENT='"+jTextField11.getText()+"' where ID_MEMBRE ='"+id+"' ;");
        
        
        
// TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(Modifier_m.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
                JFileChooser chooser = new JFileChooser();
chooser.setCurrentDirectory(new java.io.File("."));
chooser.setDialogTitle("choosertitle");
chooser.setAcceptAllFileFilterUsed(false);

if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
  file = chooser.getSelectedFile();
   path = file.getPath();
  jTextField10.setText(path);
} else {
  System.out.println("No Selection ");
}
//   String s = getpath();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      FileSystemView fileSys = FileSystemView.getFileSystemView();
    try {
    Document document=new Document(PageSize.A5);
       PdfWriter.getInstance(document,new FileOutputStream(fileSys.getHomeDirectory()+"\\fiche Membre'"+id+"'.pdf"));
       document.addAuthor("Ali-Mtibaa");
      document.addTitle("FIche");
       
       document.open();  
          ResultSet result = st.executeQuery("SELECT m.ID_MEMBRE,m.NOM,m.PRENOM,m.NUM_TEL,m.EMAIL,m.DATE_NAIS,"
                  + "m.DATE_INSC,a.ID_ABONEMENT,a.DUREE,a.TOTAL,a.ETATABONEMENT,s.NOM_S,s.NBRE_HEURE,c.NOM_C,"
                  + "c.PRENOM_C,c.NUM_TEL_C FROM membre m ,abonement a , apartient ap, sport s , coach c "
                  + "WHERE m.ID_MEMBRE = a.ID_MEMBRE AND a.ID_ABONEMENT = ap.ID_ABONEMENT AND s.ID_SPORT=ap.ID_SPORT "
                  + "AND c.ID_COACH = s.ID_COACH AND m.ID_MEMBRE ='"+id+"';");
          if (result.next()) {
       
            Paragraph p0 =new Paragraph ("*************************************************************");
            Paragraph p1 =new Paragraph ("*                               Fiche Membre                             *");
            Paragraph p2 =new Paragraph ("*************************************************************");
            Paragraph p3 =new Paragraph ("*         ID : "       +result.getString(1)                );
            Paragraph p4 =new Paragraph ("*         Nom :  "     +result.getString(2)             );
            Paragraph p5 =new Paragraph ("*         Prenom : "     +result.getString(3)                    );
            Paragraph p6 =new Paragraph ("*         Telephone : "   +result.getString(4)                        );
            Paragraph p7 =new Paragraph ("*         E-Mail : "   +result.getString(5)                        );
            Paragraph p8 =new Paragraph ("*         Date de naissance : "   +result.getString(6)                        );
            Paragraph p9 =new Paragraph ("*         Date d'inscription : "   +result.getString(7)                        );
            Paragraph p10 =new Paragraph ("*         ID Abonnement : "   +result.getString(8)                        );
            Paragraph p11 =new Paragraph ("*         Duree(mois) : "   +result.getString(9)                        );
            Paragraph p12 =new Paragraph ("*         Total payé : "   +result.getString(10)     + " DT "                   );
            Paragraph p13 =new Paragraph ("*         Etat : "   +result.getString(11)                        );
            Paragraph p14 =new Paragraph ("*         Sport : "   +result.getString(12)                        );
            Paragraph p15 =new Paragraph ("*         Nombre d'heure : "   +result.getString(13)                        );
            Paragraph p16 =new Paragraph ("*         Nom Coach : "   +result.getString(14)                        );
            Paragraph p17 =new Paragraph ("*         Prenom Coach : "   +result.getString(15)                        );
            Paragraph p18 =new Paragraph ("*         Tel Coach : "   +result.getString(16)                        );
            Paragraph p19 =new Paragraph ("*************************************************************");
            document.add(p0);
            document.add(p1);
            document.add(p2);
            document.add(p3);
            document.add(p4);
            document.add(p5);
            document.add(p6);
            document.add(p7);
            document.add(p8);
            document.add(p9);
            document.add(p10);
            document.add(p11);
            document.add(p12);
            document.add(p13);
            document.add(p14);
            document.add(p15);
            document.add(p16);
            document.add(p17);
            document.add(p18);
            document.add(p19);
           
            
          }
      
      
      JOptionPane.showMessageDialog(null,"Fiche PDF imprimée!");
      
      
      document.close(); 
    } catch (DocumentException ex) {
        Logger.getLogger(Modifier_m.class.getName()).log(Level.SEVERE, null, ex);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(Modifier_m.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Modifier_m.class.getName()).log(Level.SEVERE, null, ex);
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifier_m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifier_m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifier_m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifier_m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifier_m().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
